language: scala
jdk:
  - oraclejdk8
  - openjdk7
scala:
  - 2.10.5
  - 2.11.7
  - 2.12.0-M2
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
matrix:
  exclude:
    - jdk: openjdk7
      scala: 2.12.0-M2
