language: java
env:
  - ISABELLE_VERSION=2015 SCALA_VERSION=2.11.7
install:
  - git submodule update --init --recursive
os:
  - osx
script:
  - ./bin/travis.sh
matrix:
  include:
    - env: ISABELLE_VERSION=2014 SCALA_VERSION=2.11.7
      os: linux
      jdk: oraclejdk7
    - env: ISABELLE_VERSION=2015 SCALA_VERSION=2.10.5
      os: linux
      jdk: oraclejdk8
    - env: ISABELLE_VERSION=2015 SCALA_VERSION=2.11.7
      os: linux
      jdk: oraclejdk8
