language: scala
jdk:
  - openjdk7
  - oraclejdk8
env:
  - ISABELLE_VERSION=2014
  - ISABELLE_VERSION=2015
scala:
  - 2.10.5
  - 2.11.7
install:
  - git submodule update --init --recursive
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION "bootstrap/run $ISABELLE_VERSION"
  - sbt ++$TRAVIS_SCALA_VERSION test
